include:
  - project: eng/libadalang/libadalang
    file: /utils/gitlab-ci-common.yml

workflow:
  rules:
    # To avoid running too many pipelines, restrict the times we run one:

    # Run "trigger" pipelines
    - if: '$CI_PIPELINE_SOURCE == "pipeline"'

    # Run pipelines triggered by a merge request creation/update
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

    # Run for pushes to a branch *except* if there is also a merge request for
    # it.
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'


stages:
  - single


continuous_builder:
  extends: .cb
  stage: single
