include:
  - project: eng/libadalang/libadalang
    file: /utils/gitlab-ci-common.yml


stages:
  - issue
  - cb


issue_check:
  services:
     - image:e3
  stage: issue
  interruptible: true  # Cancel job if the branch is pushed
  variables: # do not checkout the git repository, not needed
    GIT_STRATEGY: none
  rules: # Launch only on merge requests
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - require_issue


continuous_builder:
  extends: .cb
  stage: cb
