include:
  - project: eng/libadalang/libadalang
    file: /utils/gitlab-ci-common.yml

workflow:
  rules:
    # To avoid running too many pipelines, restrict the times we run one:

    # Run "trigger" pipelines
    - if: '$CI_PIPELINE_SOURCE == "pipeline"'

    # Run pipelines triggered by a merge request creation/update
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

    # Run for pushes to a branch *except* if there is also a merge request for
    # it.
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'


stages:
  - issue
  - cb


issue_check:
  services:
     - image:e3
  stage: issue
  interruptible: true  # Cancel job if the branch is pushed
  variables: # do not checkout the git repository, not needed
    GIT_STRATEGY: none
  rules: # Launch only on merge requests
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - unset GITLAB_TOKEN; require_issue


continuous_builder:
  extends: .cb
  stage: cb
